name: almanar_application
description: Gym Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # import svg files in order to use it on the app
  flutter_svg: ^2.0.9

  # smooth indicator for onboarding screen
  smooth_page_indicator: ^1.1.0

  # good package to handle conditions, more clean code
  conditional_builder_null_safety: ^0.0.6

  # useful package for giving spaces between widgets without giving specific height or width
  gap: ^3.0.1

  # making the app responsive for multiple screens
  flutter_screenutil: ^5.9.0

  # useful state management to handle UI states
  flutter_bloc: ^8.1.3

  # beautiful verification_code widget for verification screen
  flutter_verification_code: ^1.1.7

  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.8.1

  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.4.6

  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  freezed_annotation: ^2.4.1

  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App
  get_it: ^7.6.7

  # Make animating widgets a breeze with many effects built in. Make Text animations beautiful with staggered text effects. transitions, blurs & more, animate gestures too
  widget_and_text_animator: ^1.1.5

  # Wheel Slider offers a lot of customisation and enables you to scroll around with a wheel-like appearance.
  wheel_slider: ^1.2.1

  # A highly customizable Flutter chart library that supports Line Chart, Bar Chart, Pie Chart, Scatter Chart, and Radar Chart.
  fl_chart: ^0.66.1

  # A flutter project which add scroll direction to ListWheelScrollView allowing you to have horizontal ListWheelScroolView.
  list_wheel_scroll_view_nls: ^0.0.3

  # Provides a collection of Flutter grids layouts (staggered, masonry, quilted, woven, etc.).
  flutter_staggered_grid_view: ^0.7.0

  # Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
  injectable: ^2.3.2

  # A flutter package with many country flag icons that you can use via the Image.asset method
  country_icons: ^3.0.0

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.19.0

  # A flutter package that allows you to easily create a custom scrollable list.
  expandable: ^5.0.1








  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: MyIcons
      fonts: 
        - asset: assets/icons/MyIcons.ttf

    

    

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
